# docker-compose.yaml - Run the complete application stack (v2 - Corrected)
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped # Ensures Redis comes back online if it crashes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  parlay-bot:
    build: 
      context: .
    image: parlay-bot-app:latest # Give the built image a name
    command: npm start
    ports:
      - "8080:8080" # Maps the container's port 8080 to your machine's port 8080
    env_file:
      - .env
    environment:
      - PORT=8080 # Tells the bot to listen on port 8080 inside the container
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/liveness"] # Updated to use the correct port
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  worker-odds:
    image: parlay-bot-app:latest # REUSE the image built for the main bot
    command: npm run worker:odds
    env_file:
      - .env
    depends_on:
      redis: # Workers usually only need the database, not the main app
        condition: service_healthy
    restart: unless-stopped

  worker-notifications:
    image: parlay-bot-app:latest # REUSE the image built for the main bot
    command: npm run worker:notifications
    env_file:
      - .env
    depends_on:
      redis: # Workers usually only need the database, not the main app
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data:

